# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagoMundi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfmark', models.TextField(blank=True, null=True)),
                ('date_from', models.CharField(blank=True, max_length=100, null=True)),
                ('date_until', models.CharField(blank=True, max_length=100, null=True)),
                ('current_location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('current_location_town', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_and_location_1000_1100', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_and_location_1100_1200', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_and_location_1200_1300', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_and_location_1300_1400', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_and_location_1400_1500', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_and_location_1500_1600', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_and_location_1600_1700', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_and_location_1700_1800', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_and_location_1800_1900', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_and_location_1900_2000', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('folia', models.CharField(blank=True, max_length=100, null=True)),
                ('text_type', models.CharField(blank=True, max_length=100, null=True)),
                ('chapters', models.CharField(blank=True, max_length=100, null=True)),
                ('incipit', models.TextField(blank=True, null=True)),
                ('explicit', models.TextField(blank=True, null=True)),
                ('attribution_of_author', models.CharField(blank=True, max_length=100, null=True)),
                ('decorations', models.TextField(blank=True, null=True)),
                ('manuscript_content', models.TextField(blank=True, null=True)),
                ('bibliography', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
