# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imago_mundi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagomundi',
            name='attribution_of_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='current_location_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='current_location_town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='place_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
