# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imago_mundi_app', '0002_auto_20190124_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagomundi',
            name='address_current_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagomundi',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagomundi',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
