# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imago_mundi_app', '0003_auto_20190219_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1000_1100',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1100_1200',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1200_1300',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1300_1400',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1400_1500',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1500_1600',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1600_1700',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1700_1800',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1800_1900',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='owner_and_location_1900_2000',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
