# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imago_mundi_app', '0005_auto_20190307_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagomundi',
            name='current_location_lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagomundi',
            name='current_location_lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
