# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-22 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imago_mundi_app', '0006_auto_20190313_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagomundi',
            name='attribution_of_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagomundi',
            name='chapters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
